### PR TITLE
fix(config): should not set Plugin's rule to `rules`

### LINKED ISSUE #76: ReferenceError:  overwrite config of Plugin
from: https://github.com/azu/textlint-plugin-JTF-style/pull/5#issuecomment-154417503

try to set the following and textlint throw ReferenceError.

```
{
  "plugins": [
    "jtf-style"
  ],
  "rules": {
    "jtf-style/2.1.2.漢字": {
      "severity" : "warning"
    },
    "jtf-style/4.1.1.句点(。)": false,
    "jtf-style/3.1.1.全角文字と半角文字の間": false
  }
}
```

Error mesasage:

```
[ReferenceError: rule: jtf-style/2.1.2.漢字 is not found]
```

But, following case is safe.(no error)

```
  "rules": {
    "jtf-style/2.1.2.漢字": true,
    "jtf-style/4.1.1.句点(。)": false,
    "jtf-style/3.1.1.全角文字と半角文字の間": false
  }
```

It seem bug in textlint. @ https://github.com/textlint/textlint/blob/93a70ddcbc79fef1390b5010d5a1ac7edbb78a1a/src/textlint-engine.js#L150

### PR DESCRIPTION
**Pull request by azu**
The key of Plugin's rule is `<plugin>/<rule>` that could not require.

close #76

### CODE REVIEW

File: src/config/config.js [hunk 1]
```diff
@@ -15,6 +16,10 @@ function availableRuleKeys(rulesConfig) {
         return [];
     }
     return Object.keys(rulesConfig).filter(key => {
+        // `<plugin>/<rule-key>` should ignored
+        if (isPluginRuleKey(key)) {
```
Comment (azu) [inline src/config/config.js]: add filter pattern

File: src/textlint-engine.js [hunk 2]
```diff
@@ -140,6 +141,11 @@ class TextLintEngine {
         const RULE_NAME_PREFIX = this.config.constructor.RULE_NAME_PREFIX;
         const prefixMatch = new RegExp("^" + RULE_NAME_PREFIX);
         const definedRuleName = ruleName.replace(prefixMatch, '');
+        // ignore plugin's rule
+        if (isPluginRuleKey(definedRuleName)) {
```
Comment (azu) [inline src/textlint-engine.js]: additional guard

File: test/fixtures/plugin.textlintrc [hunk 3]
```diff
@@ -4,6 +4,7 @@
     "configurable-plugin"
   ],
   "rules": {
+    "example/example-rule": true,
```
Comment (azu) [inline test/fixtures/plugin.textlintrc]: test case
