### PR TITLE
Breaking Change(filter): rename ignoring rule to filter rule

### LINKED ISSUE #211: `--fix` with ignoring rule
We have supported ignoring rule as experimental #193 

Currently, ignoring don't work with fixer.

This issue describe this bug. It is a bug of textlint-self.
https://github.com/textlint/textlint-rule-ignore-comments/issues/1

## Problem

Current, implementation of fixer.

> Parse text -> A fix rule -> re-parse text -> B fix rule ....

This design prefer much fixed than performance.

- https://github.com/textlint/textlint/blob/60633fe4530ee21e1da2d37386a568c5331f372c/src/fixer/fixer-processor.js#L36

**fixer and ignoring** 

Expected:

```
Parse text -> A fix rule -> re-parse text -> B fix rule ....
                  ^ + C ignoring rule                  ^ + C ignoring rule
```

Actual : 

> Parse text -> A fix rule -> re-parse text -> B fix rule -> re-parse text -> C ignoring rule ...

Not work ignoring.

It should be fixed

----

Edit(2016-05-26):

## Results after discussion

- Rename "ignoring rule" to "filter rule"
- Add "filters" filed support to textlint core
	- Same convention with "rules" field
- Rename "[textlint-rule-report-node-types](https://github.com/textlint/textlint-rule-report-node-types)" to "textlint-filter-rule-node-types". Is it better conventional name?
- Filter rule use `shouldIgnore(range, { ruleId })` API
  - https://github.com/textlint/textlint/blob/master/docs/rule.md
- textlint core still has actual filtering logic. - That is [message-filter.js](https://github.com/textlint/textlint/blob/master/src/shared/message-filter.js "message-filter.js")
  - [textlint-filter-plugin](https://github.com/textlint/textlint/issues/211#issuecomment-220991535) pattern is difficult.
  - We like simple.
- The order of filters doesn't affect result.
- textlint not allow (normal) rule to use `shouldIgnore`.

e.g.) The user want to use `textlint-filter-rule-node-types` and set following to  `.textlintrc` 

```json
{
   "filters": {
      "node-types": {
      	"nodeTypes": ["BlockQuote"]
      }
   }
}
```

See https://github.com/textlint/textlint/issues/211#issuecomment-221601511

### PR DESCRIPTION
**Pull request by azu**
Support "filters" field and Drop support "ignore-rule"

```js
{
   "filters": {
      "node-types": {
        "nodeTypes": ["BlockQuote"]
      }
   },
   "rules": {}
}
```

- Replace "ignoring rule" with "filter rule"
- Add "filters" filed support to textlint core
	- Same convention with "rules" field
- Rename "[textlint-rule-report-node-types](https://github.com/textlint/textlint-rule-report-node-types)" to "textlint-filter-rule-node-types". Is it better conventional name?
- Filter rule use `shouldIgnore(range, { ruleId })` API
  - https://github.com/textlint/textlint/blob/master/docs/rule.md
- textlint not allow (normal) rule to use `shouldIgnore`.

fixes #211 
refs #212

### CODE REVIEW

File: src/core/filter-rule-context.js [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+
+/**
+ * Rule context object is passed to each rule as `context`
+ * @param {string} ruleId
+ * @param {SourceCode} sourceCode
+ * @param {function(ReportIgnoreMessage)} ignoreReport
+ * @param {Config} textLintConfig
+ * @constructor
+ */
+export default function FilterRuleContext({ruleId, sourceCode, ignoreReport, textLintConfig}) {
```
Comment (azu) [inline src/core/filter-rule-context.js]: Separate Context object

File: src/engine/textlint-module-loader.js [hunk 2]
```diff
@@ -19,6 +19,7 @@ import TextLintModuleResolver from "./textlint-module-resolver";
 export const createEntities = (pluginRules, prefixKey) => {
     const entities = [];
     Object.keys(pluginRules).forEach(ruleId => {
+        // TODO: / should be module
```
Comment (azu) [inline src/engine/textlint-module-loader.js]: should be shared `mapRulesConfig`

File: src/task/textlint-core-task.js [hunk 3]
```diff
@@ -192,6 +205,19 @@ export default class TextLintCoreTask extends EventEmitter {
             const ruleObject = this.getRuleObject(ruleCreator, ruleContext, ruleConfig);
             this._addListenRule(ruleId, ruleObject);
         });
+        // setup "filters" field
+        Object.keys(filterRules).forEach(ruleId => {
```
Comment (azu) [inline src/task/textlint-core-task.js]: register "filter"

File: src/textlint-core.js [hunk 4]
```diff
@@ -91,10 +92,21 @@ export default class TextlintCore {
     }
 
     /**
+     * Register filterRules and filterRulesConfig.
+     * if want to release rules, please call {@link resetRules}.
+     * @param {object} rules rule objects array
+     * @param {object} [rulesConfig] ruleConfig is object
+     */
+    setupFilterRules(rules = {}, rulesConfig = {}) {
```
Comment (azu) [inline src/textlint-core.js]: add `setupFilterRules`

File: src/engine/textlint-engine-core.js [hunk 5]
```diff
@@ -118,6 +125,17 @@ new TextLintEngine({
         this._setupRules();
     }
 
+    /**
+     * load filter rule manually
+     * Note: it high cost, please use config
+     * @param {string} ruleName
+     * @deprecated use Constructor(config) insteadof it
```
Comment (azu) [inline src/engine/textlint-engine-core.js]: it is needed for testing. but should not used in production.
Is `deprecated` correct?

Comment (azu) [inline src/engine/textlint-engine-core.js]: We will change loading of config to async.
