### PR TITLE
fix(textlint-tester): Correct output ${text}

### LINKED ISSUE #395: textlint-tester: bad output when use `inputPath`
`inputPath` option is introduced in #394 

But, error output is bad.

https://github.com/textlint/textlint/pull/394#issuecomment-352350740

```
===Text===:
${text}
```

should be

```
const text = filePath ? fs.readFileSync(filePath, "utf-8") || text;
`
===Text===:
${text}
...
```

## Tasks

- [x] https://github.com/textlint/textlint/blob/1581a4eabd406abfd7e938aa0f61f0bcca670a50/packages/textlint-tester/src/test-util.js#L68
- [x] https://github.com/textlint/textlint/blob/1581a4eabd406abfd7e938aa0f61f0bcca670a50/packages/textlint-tester/src/test-util.js#L136

### PR DESCRIPTION
**Pull request by azu**
- [x] https://github.com/textlint/textlint/blob/1581a4eabd406abfd7e938aa0f61f0bcca670a50/packages/textlint-tester/src/test-util.js#L68
- [x] https://github.com/textlint/textlint/blob/1581a4eabd406abfd7e938aa0f61f0bcca670a50/packages/textlint-tester/src/test-util.js#L136

fix #395

### CODE REVIEW

File: packages/textlint-tester/src/test-util.js [hunk 1]
```diff
@@ -10,13 +10,13 @@ const fs = require("fs");
  * @returns {string}
  */
 function getTestText({ text, inputPath }) {
```
Comment (azu) [inline packages/textlint-tester/src/test-util.js]: Reorder.

1. check `inputPath`
2. check `text`
