### PR TITLE
fix(plugin): fix 3rd party plugin is not working

### LINKED ISSUE #180: Some plugins don't work
I'm using textlint v6.0.3. This version seems to not work plugins(More preceisely, non-embedded `Processor`).
I confirmed that it has occurred with `textlint-plugin-html` and my plugins in process of creation.

### PR DESCRIPTION
**Pull request by azu**
When load a plugin, then add available extensions like .html" to core.
But, `engine.availableExtensions` always is empty at  textlint v6.0.3.

fix #180

### CODE REVIEW

File: test/textlint-engine-test.js [hunk 1]
```diff
@@ -122,6 +122,15 @@ describe("textlint-engine-test", function () {
                 assert(engine.ruleMap.getRule("example/example-rule") === ruleObject);
             });
         });
+        context("when load html plugin", function () {
```
Comment (azu) [inline test/textlint-engine-test.js]: That is test for this bug.

**Comment by azu** [comment]
@homu r+
