### PR TITLE
 fix(textlint): add normalization for rule config key

### LINKED ISSUE #583: Severity warning is being reported as error
**What version of textlint are you using?**

v11.2.1

**What file type (Markdown, plain text, etc.) are you using?**
Markdown

**What did you do? Please include the actual source code causing the issue.**
Followed the instructions from the doc here:
https://textlint.github.io/docs/configuring.html#severity-config-of-rules

Configured `.textlintrc` for one of the rule's severity to be *warning* level instead of default *error*. Here's the copy of my `.textlintrc`
```json
{
  "rules": {
    "@textlint-rule/no-unmatched-pair": true,
    "apostrophe": true,
    "en-capitalization": true,
    "max-comma": {
      "max" : 3
    },
    "no-dead-link": {
      "checkRelative": true,
      "baseURI": null,
      "ignore": [],
      "preferGET": [],
      "ignoreRedirects": true
    },
    "no-empty-section": true,
    "textlint-rule-common-misspellings": true,
    "textlint-rule-write-good": {
      "severity": "warning" 
    }
  }
}
```

**What did you expect to happen?**
Expected to see problems found by **write-good** rule being reported as "warning"

**What actually happened? Please include the actual, raw output from textlint.**
**write-good** rule related issues are being reported as "error"

debug log:
```
  textlint:cli Running on files, stdin-filename: undefined +0ms
  textlint:module-loader config Config {
  textlint:module-loader   configFile:
  textlint:module-loader    '/Users/amimas/myproject/website/.textlintrc',
  textlint:module-loader   rulesBaseDirectory: undefined,
  textlint:module-loader   rules:
  textlint:module-loader    [ '@textlint-rule/no-unmatched-pair',
  textlint:module-loader      'apostrophe',
  textlint:module-loader      'en-capitalization',
  textlint:module-loader      'max-comma',
  textlint:module-loader      'no-dead-link',
  textlint:module-loader      'no-empty-section',
  textlint:module-loader      'textlint-rule-common-misspellings',
  textlint:module-loader      'textlint-rule-write-good' ],
  textlint:module-loader   disabledRules: [],
  textlint:module-loader   filterRules: [],
  textlint:module-loader   disabledFilterRules: [],
  textlint:module-loader   presets: [],
  textlint:module-loader   plugins: [],
  textlint:module-loader   pluginsConfig: {},
  textlint:module-loader   rulesConfig:
  textlint:module-loader    { '@textlint-rule/no-unmatched-pair': true,
  textlint:module-loader      apostrophe: true,
  textlint:module-loader      'en-capitalization': true,
  textlint:module-loader      'max-comma': { max: 3 },
  textlint:module-loader      'no-dead-link':
  textlint:module-loader       { checkRelative: true,
  textlint:module-loader         baseURI: null,
  textlint:module-loader         ignore: [],
  textlint:module-loader         preferGET: [],
  textlint:module-loader         ignoreRedirects: true },
  textlint:module-loader      'no-empty-section': true,
  textlint:module-loader      'textlint-rule-common-misspellings': true,
  textlint:module-loader      'textlint-rule-write-good': { severity: 'warning' } },
  textlint:module-loader   filterRulesConfig: {},
  textlint:module-loader   rulePaths: [],
  textlint:module-loader   formatterName: undefined,
  textlint:module-loader   quiet: false,
  textlint:module-loader   color: true,
  textlint:module-loader   cache: false,
  textlint:module-loader   cacheLocation:
  textlint:module-loader    '/Users/amimas/myproject/website/.textlintcache' } +0ms
  textlint:module-loader Loading rules from /Users/amimas/myproject/website/node_modules/@textlint-rule/textlint-rule-no-unmatched-pair/lib/textlint-rule-no-unmatched-pair.js +4ms
  textlint:module-loader Loading rules from /Users/amimas/myproject/website/node_modules/textlint-rule-apostrophe/index.js +21ms
  textlint:module-loader Loading rules from /Users/amimas/myproject/website/node_modules/textlint-rule-en-capitalization/lib/textlint-rule-en-capitalization.js +0ms
  textlint:module-loader Loading rules from /Users/amimas/myproject/website/node_modules/textlint-rule-max-comma/lib/textlint-rule-max-comma.js +370ms
  textlint:module-loader Loading rules from /Users/amimas/myproject/website/node_modules/textlint-rule-no-dead-link/lib/no-dead-link.js +3ms
  textlint:module-loader Loading rules from /Users/amimas/myproject/website/node_modules/textlint-rule-no-empty-section/lib/textlint-rule-no-empty-section.js +37ms
  textlint:module-loader Loading rules from /Users/amimas/myproject/website/node_modules/textlint-rule-common-misspellings/lib/common-misspellings.js +2ms
  textlint:module-loader Loading rules from /Users/amimas/myproject/website/node_modules/textlint-rule-write-good/lib/write-good.js +4ms
  textlint:engine-core Process files [ '/Users/amimas/myproject/docs/index.md' ] +0ms
  textlint:engine-core Not Process files [] +0ms
  textlint:TextLintCoreTask rules TextlintRuleDescriptors {
  ruleDescriptorList:
   [ TextlintLintableRuleDescriptor { textlintKernelRule: [Object] },
     TextlintFixableRuleDescriptor { textlintKernelRule: [Object] },
     TextlintFixableRuleDescriptor { textlintKernelRule: [Object] },
     TextlintLintableRuleDescriptor { textlintKernelRule: [Object] },
     TextlintFixableRuleDescriptor { textlintKernelRule: [Object] },
     TextlintLintableRuleDescriptor { textlintKernelRule: [Object] },
     TextlintFixableRuleDescriptor { textlintKernelRule: [Object] },
     TextlintFixableRuleDescriptor { textlintKernelRule: [Object] } ] } +0ms
  textlint:TextLintCoreTask filterRules TextlintFilterRuleDescriptors { ruleDescriptorList: [] } +2ms
  textlint:core-task common-misspellings pushReport {"index":35,"fix":{"range":[35,44],"text":"absolutely","isAbsolute":false}} +0ms
  textlint:core-task max-comma pushReport {"line":0,"column":184} +8ms
  textlint:core-task max-comma pushReport {"line":0,"column":268} +1ms
  textlint:core-task write-good pushReport {"index":27} +1ms
  textlint:core-task write-good pushReport {"index":111} +0ms
  textlint:core-task write-good pushReport {"index":126} +0ms
  textlint:core-task write-good pushReport {"index":290} +0ms
  textlint:core-task write-good pushReport {"index":15} +6ms
  textlint:core-task write-good pushReport {"index":195} +1ms
  textlint:core-task apostrophe pushReport {"index":7,"fix":{"range":[7,10],"text":"js’","isAbsolute":false}} +0ms
  textlint:core-task write-good pushReport {"index":18} +8ms
  textlint:core-task write-good pushReport {"index":22} +1ms
  textlint:core-task write-good pushReport {"index":72} +0ms
  textlint:core-task max-comma pushReport {"line":0,"column":0} +6ms
  textlint:core-task apostrophe pushReport {"index":381,"fix":{"range":[381,385],"text":"it’s","isAbsolute":false}} +0ms
  textlint:core-task write-good pushReport {"index":136} +0ms
  textlint:core-task write-good pushReport {"index":363} +0ms
  textlint:core-task write-good pushReport {"index":49} +2ms
  textlint:core-task write-good pushReport {"index":35} +3ms
  textlint:core-task write-good pushReport {"index":87} +0ms
  textlint:core-task write-good pushReport {"index":36} +6ms
  textlint:core-task write-good pushReport {"index":94} +2ms
  textlint:core-task write-good pushReport {"index":130} +0ms
  textlint:core-task write-good pushReport {"index":142} +0ms
  textlint:core-task write-good pushReport {"index":164} +0ms
  textlint:core-task write-good pushReport {"index":49} +8ms
  textlint:core-task write-good pushReport {"index":44} +9ms
  textlint:core-task write-good pushReport {"index":87} +0ms
  textlint:core-task write-good pushReport {"index":67} +5ms
  textlint:core-task write-good pushReport {"index":98} +3ms
  textlint:core-task write-good pushReport {"index":122} +6ms
  textlint:core-task write-good pushReport {"index":28} +1ms
  textlint:core-task write-good pushReport {"index":109} +3ms
  textlint:core-task write-good pushReport {"index":183} +0ms
  textlint:core-task write-good pushReport {"index":222} +0ms
  textlint:core-task write-good pushReport {"index":158} +4ms
  textlint:core-task write-good pushReport {"index":167} +0ms
  textlint:core-task write-good pushReport {"index":37} +3ms
  textlint:core-task write-good pushReport {"index":33} +2ms
  textlint:core-task write-good pushReport {"index":52} +0ms
  textlint:core-task write-good pushReport {"index":146} +0ms
  textlint:@textlint/linter-formatter try formatterName: stylish +0ms

/Users/amimas/myproject/docs/index.md
   9:36   ✓ error  This is a commonly misspelled word. Correct it to absolutely    common-misspellings
  11:28   error    "is composed" may be passive voice                              write-good
  11:112  error    "is composed" may be passive voice                              write-good
  11:127  error    "various" is a weasel word                                      write-good
```

### PR DESCRIPTION
**Pull request by azu**
This PR will fix to work correctly. #583 

```json
{
  "rules": {
    "textlint-rule-common-misspellings": true,
    "textlint-rule-write-good": {
      "severity": "warning" 
    }
  }
}
```

This PR includes refactoring codes.
I describe the design of Key resolving algorithm.

### Key normalization algorithm

**key**: key is normalized string for resolving {rule,filterRule,plugin} option.
The key is shorten by design.
For example, `@org/textlint-rule-preset-parent`'s `@org/textlint-rule-child` key is `@org/parent/@org/child`.
`@org/textlint-rule-preset-parent`'s `@org/textlint-rule-child`:
```json
{
 "rules": {
   "@org/textlint-rule-preset-parent": {
      "@org/textlint-rule-child": true
   }
 }
```
In internal, this config is normalized to following:
```
{ @org/parent/@org/child: true }
```
For more details, see textlint-package-name-util-test.ts
**Related:**
- <https://github.com/textlint/textlint/issues/583>
- <https://github.com/textlint/textlint/pull/586>

fix #583

### CODE REVIEW

File: packages/textlint/test/cli/cli-test.ts [hunk 1]
```diff
@@ -57,6 +57,32 @@ describe("cli-test", function() {
...
+                    {
+                        filePath: targetFile,
+                        messages: [
+                            {
+                                column: 3,
+                                index: 17,
+                                line: 3,
+                                message: "Found TODO: '- [ ] TODO'",
+                                ruleId: "no-todo",
+                                severity: 1,
```
Comment (azu) [inline packages/textlint/test/cli/cli-test.ts]: `warning`

File: packages/textlint/src/config/config.ts [hunk 2]
```diff
@@ -123,41 +118,6 @@ export class Config {
         return "textlint";
     }
 
-    /**
-     * @return {string} config package prefix
-     */
-    static get CONFIG_PACKAGE_PREFIX() {
```
Comment (azu) [inline packages/textlint/src/config/config.ts]: This definition is moved to pacakge-prefix.ts

At first, we introduce this constnats value for abstraction.
But, we have a kernel module. The abstraction is not need anymore.

File: packages/textlint/test/config-key-normalizer/config-key-normalizer-test.ts [hunk 3]
```diff
@@ -0,0 +1,162 @@
...
+type NormalizeFunction = (name: string) => string;
+const checkPatterns = (normalizeFunction: NormalizeFunction, patterns: { before: string; after: string }[]) => {
+    patterns.forEach(pattern => {
+        it(`${pattern.before} -> ${pattern.after}`, () => {
+            assert.strictEqual(normalizeFunction(pattern.before), pattern.after);
+        });
+    });
+};
+
+describe("config-key-normalizer", function() {
```
Comment (azu) [inline packages/textlint/test/config-key-normalizer/config-key-normalizer-test.ts]: normalization tests!
